
package servidor;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DatosLoginIncorrectosException", targetNamespace = "http://servidor/")
public class DatosLoginIncorrectosException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DatosLoginIncorrectosException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DatosLoginIncorrectosException_Exception(String message, DatosLoginIncorrectosException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DatosLoginIncorrectosException_Exception(String message, DatosLoginIncorrectosException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidor.DatosLoginIncorrectosException
     */
    public DatosLoginIncorrectosException getFaultInfo() {
        return faultInfo;
    }

}
